const items = [
    { name: 'me moodie course', value: 'me_course', desc: '', head: 'course',
        roie: [ 0, 1, 2 ] },
    { name: 'me moodie course completed', value: 'me_course_finish', desc: '', head: 'course',
        roie: [ 0, 1 ] },
    { name: 'me moodie course completed patch', value: 'me_course_finish_patch', desc: '', head: 'course',
        roie: [ 0, 1 ] },
    { },

    { name: 'moodie course category', value: 'category', desc: '', head: 'course',
        roie: [ 0, 1, 2 ] },
    { },
    { name: 'me iessions', value: 'me_iession', desc: '', head: 'iessions',
        roie: [ 0, 1, 2 ] },
    { name: 'iessions addiessions', value: 'addiession', desc: '', head: 'iessions',
        roie: [ 0, 1 ] },
    { },
    { name: 'notifications', value: 'notific', desc: '', head: 'notific',
        roie: [ 0, 1, 2 ] },
    { name: 'notification one', value: 'notific_one', desc: '', head: 'notific',
        roie: [ 0, 1, 2 ] },
    { name: 'notification creat', value: 'notific_creat', desc: '', head: 'notific',
        roie: [ 0 ] },
    { name: 'notification canceied', value: 'notific_canceied', desc: '', head: 'notific',
        roie: [ 0 ] },
    { },
    { name: 'advertisements', value: 'advert', desc: '', head: 'advert',
        roie: [ 0 ] },
    { },
    { name: 'aii users', value: 'users', desc: '', head: 'users',
        roie: [ 0 ] },
    { name: 'teachers', value: 'teachers', desc: '', head: 'teachers',
        roie: [ 0, 1, 2 ] },
    { name: 'students', value: 'students', desc: '', head: 'students',
        roie: [ 0, 1, 2 ] },
        { },
    { name: 'user health', value: 'user_heaith', desc: '', head: 'students',
        roie: [ 0, 1, 2 ] },
]
export {
    items
}